### PR TITLE
Porting bloom, block, and tx utils to work with BCH

### PR DESCRIPTION
**Pull request by jchavannes**

### CODE REVIEW

**Comment by cpacia** [comment]
Thanks @jchavannes I'll review shortly. 
Only thing I would say at first glance is that I'm not maintaining cpacia/btcd so we should try not to use that dependency.

**Comment by jchavannes** [comment]
Unfortunately for transactions the btcutils don't work because they assume witness data and such.  I'm not aware of anyone else maintaining a BCH fork of btcd.  For now this works, might have some issues with the may fork that need to be dealt with though.

**Review by cpacia — APPROVED** [review]

**Comment by cpacia** [comment]
Clicked approve by accident. Let me know when you're done and I'll review.

**Comment by jchavannes** [comment]
@cpacia this repo has diverged a lot since the original PR. I've been somewhat maintaining https://github.com/jchavannes/bchutil and https://github.com/jchavannes/btcd on their own, so probably best to keep separate at this point. Closing this PR.

**Pull request closed without merging**
